version: '3'

networks:
  database:
    driver: bridge
  decision:
    driver: bridge

services:
  aichat:
    container_name: aichat
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 9090:9090
    volumes:
      - .:/app
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_DBNAME=allychat
      - OPENAPI_KEY=xxx
    networks:
      - database
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: allychat
      # MYSQL_USER: mitch
      # MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode=""
    healthcheck:
      test: []
      timeout: 5s
      retries: 10
    networks:
      database:
        aliases:
          - database


